### ISSUE TITLE
Timeout while deploying

### ISSUE THREAD

**Issue by jmendiara** [nalbion/serverless-plugin-encrypted#3]
When including this plugin, the serverless deploy may fail cause a timeout
probably the cause is
https://github.com/nalbion/serverless-plugin-encrypted/blob/master/index.js#L12

that sets the timeout for the whole sdk, interfering in others plugins behaviours

**Comment by nalbion** [comment]
@jmendiara I've made the AWS_TIMEOUT optional in 1.0.5
